# @package _global_
datamodule:
  train_data_source:
    image_clip_ids: [ -16, 0]
    bbox_clip_ids: [ 1, 8 ]
    image_clip_fn:
      _target_: src.datamodules.clip_functions.sample
      _partial_: True
      _convert_: partial
      steps:
        - [ 0, 1, 10, -2, -1, 0 ]
        - [ 0, 0.2, 5, -16, -8, 0 ]
        - [ 0, 0.4, 5, -8, -4, 0 ]
        - [ 0, 0.6, 5, -4, -2, 0 ]
    bbox_clip_fn:
      _target_: src.datamodules.clip_functions.sample
      _partial_: True
      _convert_: partial
      steps:
        - [ 0, 1, 10, 0, 1, 2, 4, 8 ]
  val_data_source:
    image_clip_ids: [ -2, -1, 0 ]
    bbox_clip_ids: [ 1, 2, 4, 8 ]
  test_data_source:
    image_clip_ids: [ -2, -1, 0 ]
    bbox_clip_ids: [ 1, 2, 4, 8 ]

model:
  metric:
    future_time_constant: [ 1, 2, 4, 8 ]

sap_strategy:
  past_length: 3
  future_length: 4
